44 research rule mining
AllanNastin/ethical-ai pull request #82
Opened 2024-03-24 23:29 UTC by faitholopade

2024-03-25 14:19 UTC, lizchow1 submitted a review, later dismissed

2024-03-25 15:00 UTC, rbarrtcd requested changes
Reccomend testing pdf_to_str with raw_text = True, before using pdf_to_text. If that doesn't work, I recommend renaming the files to indicate their exact purpose.

2024-03-26 13:35 UTC, rbarrtcd approved these changes

2024-03-26 13:36 UTC, AllanNastin approved these changes

2024-03-26 13:36 UTC, merged