23 develop a function to automate bio labeling process
AllanNastin/ethical-ai pull request #86
Opened 2024-03-26 14:03 UTC by lizchow1

2024-03-26 14:04 UTC, rbarrtcd submitted a review, later dismissed

2024-03-27 16:42 UTC, faitholopade requested changes
Refactor auto_label_function.py def set_to_lower(): var names to resolve conflict

2024-03-27 16:42 UTC, faitholopade commented on backend/auto_label_function.py
> +def set_to_lower():
Refactor variable name conflict

2024-03-29 08:45 UTC, faitholopade submitted a review, later dismissed

2024-03-29 09:06 UTC, AllanNastin approved these changes

2024-03-29 09:07 UTC, merged